language: python
python:
    - "3.4"

install:
    - python3 setup.py install
    - pip install python-coveralls pytest-cov

script:
    - py.test -v --cov resolver_deco --cov-report term-missing

after_success:
    - coveralls
